# permissions for end users to edit suites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suite-editor-role
rules:
- apiGroups:
  - testing.tsgpragc.com
  resources:
  - suites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testing.tsgpragc.com
  resources:
  - suites/status
  verbs:
  - get
